# Generated by Django 4.1.2 on 2023-08-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_implement_tasks', 'To earn money$'), ('can_create_tasks', 'To create tools'), ('can_use_business_interface', 'To use creators tools'))},
        ),
    ]
