# Generated by Django 4.2.3 on 2023-07-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person_name2_alter_person_name'),
        ('polls', '0003_alter_person_name'),
    ]

    operations = [
    ]
