# Generated by Django 4.2.3 on 2023-07-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_merge_20230716_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name2',
        ),
    ]
