# Generated by Django 4.2.3 on 2023-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_person_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='1', max_length=100, unique=True),
        ),
    ]
