# Generated by Django 4.1.2 on 2023-08-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_organization_order_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_link', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('repeat_time_plan', models.PositiveSmallIntegerField()),
                ('repeat_time_fact', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.order')),
            ],
        ),
    ]
