# Generated by Django 4.1.2 on 2023-08-17 10:51

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='file_link',
            field=models.FileField(upload_to=polls.models.user_directory_path),
        ),
    ]
