# Generated by Django 4.1.2 on 2023-08-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_avatar'),
        ('polls', '0009_alter_source_file_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Form',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ST', 'Started'), ('DN', 'DN'), ('LS', 'Lost')], default='ST', max_length=2)),
                ('start_DateTime', models.DateTimeField(auto_now_add=True)),
                ('end_DateTime', models.DateTimeField()),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.form')),
            ],
        ),
    ]
