# Generated by Django 4.1.2 on 2023-08-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_task_status_reservedsource_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='s_type',
            field=models.CharField(choices=[('OC', 'One Choice'), ('MC', 'Many Choises')], default='OC', max_length=2),
            preserve_default=False,
        ),
    ]
