# Generated by Django 4.1.2 on 2023-08-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_source_s_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='org_id',
            new_name='org',
        ),
    ]
