# Generated by Django 4.1.2 on 2023-08-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_org_id_order_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='s_type',
            field=models.CharField(choices=[('IM', 'Inage'), ('VD', 'Videos')], max_length=2),
        ),
    ]
