# Generated by Django 4.1.2 on 2023-08-17 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_avatar'),
        ('polls', '0014_alter_source_s_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
    ]
