# Generated by Django 4.1.2 on 2023-08-18 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_organization_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=1000, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='bio',
            field=models.CharField(default='No bio', max_length=1000, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('CD', 'CD'), ('BD', 'Banned')], default='CR', max_length=2),
        ),
    ]
