# Generated by Django 4.1.2 on 2023-08-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_order_instruction_order_instruction_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
