# Generated by Django 4.1.2 on 2023-08-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_file_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
