# Generated by Django 4.1.2 on 2023-08-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_source_source_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('OG', 'On going'), ('ST', 'Stopped')], default='OG', max_length=2),
        ),
    ]
