# Generated by Django 4.1.2 on 2023-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_source_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Задание на разметку', max_length=50),
        ),
    ]
