# Generated by Django 4.1.2 on 2023-08-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='source',
        ),
        migrations.AddField(
            model_name='answer',
            name='res_source',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.reservedsource'),
            preserve_default=False,
        ),
    ]
