# Generated by Django 4.1.2 on 2023-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_remove_answer_source_answer_res_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
