# Generated by Django 4.1.2 on 2023-09-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_task_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('PB', 'Published'), ('BD', 'Banned'), ('LM', 'Low balance'), ('ND', 'No data for arrange')], default='CR', max_length=2),
        ),
    ]
