# Generated by Django 4.1.2 on 2023-09-13 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservedsource',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='s_type',
            field=models.CharField(choices=[('IM', 'Image'), ('VD', 'Videos')], max_length=2),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_sum', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=models.SET(1), to='polls.organization')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task', unique=True)),
            ],
        ),
    ]
