# Generated by Django 4.1.2 on 2023-09-13 22:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='s_type',
            field=models.CharField(choices=[('IM', 'Image'), ('VD', 'Videos')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('RS', 'Reserved'), ('CN', 'Canceled'), ('DN', 'Done'), ('ST', 'ST')], default='RS', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task', unique=True),
        ),
    ]
