# Generated by Django 4.1.2 on 2023-09-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task', unique=True),
        ),
    ]
