# Generated by Django 4.1.2 on 2023-09-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_reservedsource_created_at_reservedsource_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('RS', 'Reserved'), ('CN', 'Canceled'), ('DN', 'Done')], default='RS', max_length=2),
        ),
    ]
