# Generated by Django 4.1.2 on 2023-09-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_reservedsource_created_at_reservedsource_modified_at_and_more'),
        ('polls', '0031_alter_transaction_task'),
    ]

    operations = [
    ]
